/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package whereabout.view;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import whereabout.daoImpl.transaksi.WhereaboutDaoImpl;

/**
 *
 * @author khoerulAbu
 */
public class PanelWhereabout extends javax.swing.JPanel {
    
    WhereaboutDaoImpl whereaboutDaoImpl = new WhereaboutDaoImpl();
    

    
    public String nikKaryawan;
    /**
     * Creates new form PanelWhereabout
     */
    public PanelWhereabout() {
        initComponents();
        sub_panel_.setVisible(false);
        whereaboutDaoImpl.Tabel(this);
        setTime();
        
    }
    
    private void setTime(){
        String timeStamp = new SimpleDateFormat("HH:mm").format(Calendar.getInstance().getTime());
        field_jam_pergi.setText(timeStamp);
        field_jam_kembali.setText(timeStamp);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_whereabout = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        sub_panel_ = new javax.swing.JTabbedPane();
        sub_panel_whereabout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        field_tujuan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        field_deskripsi = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        field_jam_pergi = new javax.swing.JTextField();
        field_jam_kembali = new javax.swing.JTextField();
        sub_panel_infomasi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_nik = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_tujuan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_jam_pergi = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_jam_kembali = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        field_isi_deskripsi = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        lbl_tanggal_buat = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        field_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();

        tabel_whereabout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_whereabout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_whereaboutMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_whereabout);

        jButton1.setText("Buat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tujuan");

        field_tujuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_tujuanKeyReleased(evt);
            }
        });

        jLabel2.setText("Deskripsi");

        field_deskripsi.setColumns(20);
        field_deskripsi.setRows(5);
        field_deskripsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_deskripsiKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(field_deskripsi);

        jLabel3.setText("Jam Keluar");

        jLabel4.setText("Jam Kembali");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        field_jam_pergi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_jam_pergiActionPerformed(evt);
            }
        });
        field_jam_pergi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                field_jam_pergiKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout sub_panel_whereaboutLayout = new javax.swing.GroupLayout(sub_panel_whereabout);
        sub_panel_whereabout.setLayout(sub_panel_whereaboutLayout);
        sub_panel_whereaboutLayout.setHorizontalGroup(
            sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sub_panel_whereaboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sub_panel_whereaboutLayout.createSequentialGroup()
                        .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(field_jam_kembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(field_jam_pergi, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(sub_panel_whereaboutLayout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        sub_panel_whereaboutLayout.setVerticalGroup(
            sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sub_panel_whereaboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(field_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(field_jam_pergi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(field_jam_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sub_panel_whereaboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_batal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sub_panel_.addTab("Whereabout", sub_panel_whereabout);

        jLabel5.setText("NIK");

        jLabel6.setText(":");

        lbl_nik.setText("#NIK");

        jLabel8.setText("NAMA");

        jLabel9.setText(":");

        lbl_nama.setText("#NAMA");

        lbl_tujuan.setText("#TUJUAN");

        jLabel12.setText("TUJUAN");

        jLabel13.setText(":");

        jLabel14.setText("DESKRIPSI");

        jLabel15.setText(":");

        jLabel17.setText(":");

        lbl_jam_pergi.setText("#JAM PERGI");

        jLabel19.setText("JAM PERGI");

        jLabel20.setText(":");

        jLabel21.setText("JAM KEMBALI");

        lbl_jam_kembali.setText("#JAM KEMBALI");

        field_isi_deskripsi.setColumns(20);
        field_isi_deskripsi.setRows(5);
        jScrollPane3.setViewportView(field_isi_deskripsi);

        jLabel22.setText("TANGGAL BUAT");

        lbl_tanggal_buat.setText("#TANGGAL BUAT");

        jLabel18.setText(":");

        javax.swing.GroupLayout sub_panel_infomasiLayout = new javax.swing.GroupLayout(sub_panel_infomasi);
        sub_panel_infomasi.setLayout(sub_panel_infomasiLayout);
        sub_panel_infomasiLayout.setHorizontalGroup(
            sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sub_panel_infomasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nik)
                    .addComponent(lbl_nama)
                    .addComponent(lbl_tujuan)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_jam_pergi)
                    .addComponent(lbl_jam_kembali)
                    .addComponent(lbl_tanggal_buat))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        sub_panel_infomasiLayout.setVerticalGroup(
            sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sub_panel_infomasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lbl_nik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(lbl_nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(lbl_tujuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel18)
                    .addComponent(lbl_tanggal_buat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(lbl_jam_pergi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sub_panel_infomasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(lbl_jam_kembali))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        sub_panel_.addTab("Informasi", sub_panel_infomasi);

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(sub_panel_)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(field_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cari)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sub_panel_)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        sub_panel_.setVisible(false);
    }//GEN-LAST:event_btn_batalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        sub_panel_.remove(sub_panel_whereabout);
        sub_panel_.remove(sub_panel_infomasi);
        sub_panel_.addTab("Whereabout", sub_panel_whereabout);
        sub_panel_.setVisible(true);
        setTime();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void field_tujuanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_tujuanKeyReleased
      String tujuan=field_tujuan.getText().toUpperCase();
      field_tujuan.setText( tujuan );
    }//GEN-LAST:event_field_tujuanKeyReleased

    private void field_deskripsiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_deskripsiKeyReleased
        // TODO add your handling code here:
      String deskripsi=field_deskripsi.getText().toUpperCase();
      field_deskripsi.setText( deskripsi );
    }//GEN-LAST:event_field_deskripsiKeyReleased

    private void field_jam_pergiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_jam_pergiKeyReleased
        // TODO add your handling code here:
     
      StringBuilder sb = new StringBuilder();
      String jamPergi=field_jam_pergi.getText().toUpperCase();
      if(jamPergi.length() == 4){
          sb.append(jamPergi.substring(0, 2)).append(":").append(jamPergi.substring(2));
           field_jam_pergi.setText(sb.toString());
      }
      else {
          field_jam_pergi.setText(jamPergi);
      }
     
    }//GEN-LAST:event_field_jam_pergiKeyReleased

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
       whereaboutDaoImpl.requestLeave(this);
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
       whereaboutDaoImpl.Tabel(this);
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tabel_whereaboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_whereaboutMouseClicked
        sub_panel_.remove(sub_panel_whereabout);
        sub_panel_.remove(sub_panel_infomasi);
        sub_panel_.addTab("Informasi", sub_panel_infomasi);
        sub_panel_.setVisible(true);
        whereaboutDaoImpl.tableKlik(this);
    }//GEN-LAST:event_tabel_whereaboutMouseClicked

    private void field_jam_pergiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_jam_pergiActionPerformed
      
    }//GEN-LAST:event_field_jam_pergiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_batal;
    public javax.swing.JButton btn_cari;
    public javax.swing.JButton btn_simpan;
    public javax.swing.JTextField field_cari;
    public javax.swing.JTextArea field_deskripsi;
    public javax.swing.JTextArea field_isi_deskripsi;
    public javax.swing.JTextField field_jam_kembali;
    public javax.swing.JTextField field_jam_pergi;
    public javax.swing.JTextField field_tujuan;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lbl_jam_kembali;
    public javax.swing.JLabel lbl_jam_pergi;
    public javax.swing.JLabel lbl_nama;
    public javax.swing.JLabel lbl_nik;
    public javax.swing.JLabel lbl_tanggal_buat;
    public javax.swing.JLabel lbl_tujuan;
    public javax.swing.JTabbedPane sub_panel_;
    public javax.swing.JPanel sub_panel_infomasi;
    public javax.swing.JPanel sub_panel_whereabout;
    public javax.swing.JTable tabel_whereabout;
    // End of variables declaration//GEN-END:variables
}
