/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package whereabout.view;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import whereabout.daoImpl.KaryawanDaoImpl;

/**
 *
 * @author khoerulAbu
 */
public class PanelHc extends javax.swing.JPanel {

     private final KaryawanDaoImpl karyawanDaoImpl = new KaryawanDaoImpl();
    /**
     * Creates new form PanelWhereabout
     */
    public PanelHc() {
        initComponents();
        karyawanDaoImpl.Tabel(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_panel_hc = new javax.swing.JTable();
        field_cari_panel_hc = new javax.swing.JTextField();
        btn_cari_panel_hc = new javax.swing.JButton();
        btn_tambah_karyawan_panel_hc = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        subPanelHc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        field_nama_path_file = new javax.swing.JTextField();
        btn_browse_panel_hc = new javax.swing.JButton();
        btn_upload_panel_hc = new javax.swing.JButton();
        btn_batal_panel_hc = new javax.swing.JButton();
        subPanelHcInformasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_isi_kode = new javax.swing.JLabel();
        lbl_isi_nama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_tgl_lahir = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_tempat_lahir = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_jk = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_tgl_gabung = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_tgl_keluar = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbl_nomor_hp = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbl_status_kerja = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea_isi_alamat = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lbl_create = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lbl_update = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        lbl_role = new javax.swing.JLabel();

        tabel_panel_hc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_panel_hc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_panel_hcMouseClicked(evt);
            }
        });
        tabel_panel_hc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabel_panel_hcKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabel_panel_hcKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_panel_hc);

        btn_cari_panel_hc.setText("Cari");
        btn_cari_panel_hc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_panel_hcActionPerformed(evt);
            }
        });

        btn_tambah_karyawan_panel_hc.setText("Tambah");
        btn_tambah_karyawan_panel_hc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_karyawan_panel_hcActionPerformed(evt);
            }
        });

        jLabel2.setText("File Uploader");

        field_nama_path_file.setEditable(false);

        btn_browse_panel_hc.setText("Browse");
        btn_browse_panel_hc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browse_panel_hcActionPerformed(evt);
            }
        });

        btn_upload_panel_hc.setText("Upload");
        btn_upload_panel_hc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upload_panel_hcActionPerformed(evt);
            }
        });

        btn_batal_panel_hc.setText("Batal");
        btn_batal_panel_hc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_panel_hcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelHcLayout = new javax.swing.GroupLayout(subPanelHc);
        subPanelHc.setLayout(subPanelHcLayout);
        subPanelHcLayout.setHorizontalGroup(
            subPanelHcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelHcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelHcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelHcLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(field_nama_path_file, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_browse_panel_hc))
                    .addGroup(subPanelHcLayout.createSequentialGroup()
                        .addComponent(btn_upload_panel_hc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal_panel_hc)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        subPanelHcLayout.setVerticalGroup(
            subPanelHcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelHcLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(subPanelHcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(field_nama_path_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_browse_panel_hc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelHcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_upload_panel_hc)
                    .addComponent(btn_batal_panel_hc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tambah Karyawan", subPanelHc);

        jLabel1.setText("KODE");

        jLabel3.setText(":");

        lbl_isi_kode.setText("#KODE");

        lbl_isi_nama.setText("#NAMA");

        jLabel6.setText("NAMA");

        jLabel7.setText(":");

        jLabel8.setText("TANGGAL LAHIR");

        jLabel9.setText(":");

        lbl_tgl_lahir.setText("#TANGGAL LAHIR");

        jLabel11.setText(":");

        jLabel12.setText("TEMPAT LAHIR");

        lbl_tempat_lahir.setText("#TEMPAT LAHIR");

        jLabel14.setText("JENIS KELAMIN");

        lbl_jk.setText("#JENIS KELAMIN");

        jLabel16.setText(":");

        lbl_tgl_gabung.setText("#TANGGAL GABUNG");

        jLabel18.setText(":");

        jLabel19.setText("TANGGAL GABUNG");

        lbl_tgl_keluar.setText("#TANGGAL KELUAR");

        jLabel21.setText(":");

        jLabel22.setText("TANGGAL KELUAR");

        jLabel23.setText("EMAIL");

        jLabel24.setText(":");

        lbl_email.setText("#EMAIL");

        jLabel29.setText("NOMOR HP");

        jLabel30.setText(":");

        lbl_nomor_hp.setText("#NOMOR HP");

        jLabel32.setText(":");

        lbl_status.setText("#STATUS");

        jLabel34.setText("STATUS");

        lbl_status_kerja.setText("#STATUS KERJA");

        jLabel36.setText("STATUS KERJA");

        jLabel37.setText(":");

        jLabel38.setText("ALAMAT");

        jLabel39.setText(":");

        textArea_isi_alamat.setEditable(false);
        textArea_isi_alamat.setColumns(20);
        textArea_isi_alamat.setRows(5);
        jScrollPane2.setViewportView(textArea_isi_alamat);

        jLabel40.setText("TANGGAL INPUT");

        jLabel41.setText(":");

        lbl_create.setText("#TANGGAL INPUT");

        jLabel42.setText("TANGGAL UPDATE");

        jLabel43.setText(":");

        lbl_update.setText("#TANGGAL UPDATE");

        jLabel44.setText("ROLE");

        jLabel45.setText(":");

        lbl_role.setText("#ROLE");

        javax.swing.GroupLayout subPanelHcInformasiLayout = new javax.swing.GroupLayout(subPanelHcInformasi);
        subPanelHcInformasi.setLayout(subPanelHcInformasiLayout);
        subPanelHcInformasiLayout.setHorizontalGroup(
            subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelHcInformasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel40)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelHcInformasiLayout.createSequentialGroup()
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_isi_kode)
                            .addComponent(lbl_isi_nama)
                            .addComponent(lbl_tgl_lahir)
                            .addComponent(lbl_tempat_lahir)
                            .addComponent(lbl_jk)
                            .addComponent(lbl_tgl_gabung)
                            .addComponent(lbl_tgl_keluar)
                            .addComponent(lbl_email)))
                    .addGroup(subPanelHcInformasiLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_create))
                    .addGroup(subPanelHcInformasiLayout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_update)))
                .addGap(26, 26, 26)
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36)
                    .addComponent(jLabel38)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelHcInformasiLayout.createSequentialGroup()
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel32)
                            .addComponent(jLabel30)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nomor_hp)
                            .addComponent(lbl_status)
                            .addComponent(lbl_status_kerja)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(subPanelHcInformasiLayout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_role)))
                .addContainerGap())
        );
        subPanelHcInformasiLayout.setVerticalGroup(
            subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelHcInformasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(lbl_isi_kode)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(lbl_nomor_hp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lbl_isi_nama)
                    .addComponent(jLabel34)
                    .addComponent(jLabel32)
                    .addComponent(lbl_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(lbl_tgl_lahir)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(lbl_status_kerja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelHcInformasiLayout.createSequentialGroup()
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(lbl_tempat_lahir)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(lbl_jk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(lbl_tgl_gabung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(lbl_tgl_keluar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(lbl_email)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(lbl_create))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(jLabel45)
                        .addComponent(lbl_role))
                    .addGroup(subPanelHcInformasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42)
                        .addComponent(jLabel43)
                        .addComponent(lbl_update)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Informasi Karyawan", subPanelHcInformasi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(field_cari_panel_hc, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cari_panel_hc))
                            .addComponent(btn_tambah_karyawan_panel_hc))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_cari_panel_hc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_panel_hc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tambah_karyawan_panel_hc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_browse_panel_hcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browse_panel_hcActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            field_nama_path_file.setText(selectedFile.getAbsolutePath().replace("\\", "/"));
        }
    }//GEN-LAST:event_btn_browse_panel_hcActionPerformed

    private void btn_upload_panel_hcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upload_panel_hcActionPerformed
        karyawanDaoImpl.loadRecord(this);
    }//GEN-LAST:event_btn_upload_panel_hcActionPerformed

    private void btn_tambah_karyawan_panel_hcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_karyawan_panel_hcActionPerformed
        jTabbedPane1.setVisible(true);
        jTabbedPane1.remove(subPanelHc);
        jTabbedPane1.remove(subPanelHcInformasi);
        jTabbedPane1.addTab("Upload Data", subPanelHc);
        btn_tambah_karyawan_panel_hc.setEnabled(false);
    }//GEN-LAST:event_btn_tambah_karyawan_panel_hcActionPerformed

    private void btn_cari_panel_hcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_panel_hcActionPerformed
        // TODO add your handling code here:
        karyawanDaoImpl.Tabel(this);
    }//GEN-LAST:event_btn_cari_panel_hcActionPerformed

    private void btn_batal_panel_hcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_panel_hcActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setVisible(false);
        btn_tambah_karyawan_panel_hc.setEnabled(true);
    }//GEN-LAST:event_btn_batal_panel_hcActionPerformed

    private void tabel_panel_hcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_panel_hcMouseClicked
       
        karyawanDaoImpl.tableKlik(this);
     
    }//GEN-LAST:event_tabel_panel_hcMouseClicked

    private void tabel_panel_hcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel_panel_hcKeyPressed
      
    }//GEN-LAST:event_tabel_panel_hcKeyPressed

    private void tabel_panel_hcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel_panel_hcKeyReleased
          karyawanDaoImpl.tableKlik(this);
    }//GEN-LAST:event_tabel_panel_hcKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_batal_panel_hc;
    public javax.swing.JButton btn_browse_panel_hc;
    public javax.swing.JButton btn_cari_panel_hc;
    public javax.swing.JButton btn_tambah_karyawan_panel_hc;
    public javax.swing.JButton btn_upload_panel_hc;
    public javax.swing.JTextField field_cari_panel_hc;
    public javax.swing.JTextField field_nama_path_file;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lbl_create;
    public javax.swing.JLabel lbl_email;
    public javax.swing.JLabel lbl_isi_kode;
    public javax.swing.JLabel lbl_isi_nama;
    public javax.swing.JLabel lbl_jk;
    public javax.swing.JLabel lbl_nomor_hp;
    public javax.swing.JLabel lbl_role;
    public javax.swing.JLabel lbl_status;
    public javax.swing.JLabel lbl_status_kerja;
    public javax.swing.JLabel lbl_tempat_lahir;
    public javax.swing.JLabel lbl_tgl_gabung;
    public javax.swing.JLabel lbl_tgl_keluar;
    public javax.swing.JLabel lbl_tgl_lahir;
    public javax.swing.JLabel lbl_update;
    public javax.swing.JPanel subPanelHc;
    public javax.swing.JPanel subPanelHcInformasi;
    public javax.swing.JTable tabel_panel_hc;
    public javax.swing.JTextArea textArea_isi_alamat;
    // End of variables declaration//GEN-END:variables
}
